### ISSUE TITLE
Problem 1 Static?

### ISSUE THREAD

**Issue by sptobey** [shatterspike1/OoDAHW3#1]
Doesn't the private instance need to be static?  Also, does there need to be a public static method for getting the unique instance -- e.g. "public static SingleQueue getUniqueSingleQueue() {}" -- or is this not needed?

**Comment by shatterspike1** [comment]
There's no need for a get method for the singleton class, since we only care about what it produces, not how it functions.  You're right that the variable needs to be static though, I'll fix that.
